<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.cjc.nimbus</groupId>
    <artifactId>nimbus-server</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>api</module>
        <module>business</module>
        <module>infrastructure</module>
        <module>system</module>
        <module>upgrade</module>
    </modules>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <revision>1.0-SNAPSHOT</revision>
        <java.version>17</java.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <lombok.version>1.18.32</lombok.version>
        <springdoc.version>1.7.0</springdoc.version>
        <spring.context.version>6.2.8</spring.context.version>
        <spring.web.version>6.2.8</spring.web.version>
        <spring.webmvc.version>6.1.14</spring.webmvc.version>
        <knife4j.version>4.5.0</knife4j.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <jackson.version>2.13.0</jackson.version>
        <mapstruct.version>1.5.5.Final</mapstruct.version>
        <jmolecules-bom.version>2023.1.3</jmolecules-bom.version>
        <redisson.version>3.31.0</redisson.version>
        <jackson.version>2.17.1</jackson.version>
        <httpclient.version>4.5.13</httpclient.version>
        <jjwt.version>0.9.1</jjwt.version>
        <hutool.version>5.8.28</hutool.version>
        <p6spy.version>3.8.6</p6spy.version>
        <easyexcel.version>4.0.3</easyexcel.version>
        <maven.compiler.plugin.version>3.11.0</maven.compiler.plugin.version>
        <therapi.runtime.javadoc.scribe.version>0.15.0</therapi.runtime.javadoc.scribe.version>
        <httpclient5.version>5.3.1</httpclient5.version>
        <mybatis.plus.version>3.5.8</mybatis.plus.version>
        <mybatis-spring.version>3.0.3</mybatis-spring.version>
        <aspectjweaver.version>1.9.22</aspectjweaver.version>
        <mybatisplus.plus.version>1.7.4-RELEASE</mybatisplus.plus.version>
        <spring.aop.version>6.1.8</spring.aop.version>
        <ttl.version>2.14.4</ttl.version>
        <javamelody.version>2.3.0</javamelody.version>
        <lexorank4j.version>0.1.0</lexorank4j.version>
        <ip2region.version>2.7.0</ip2region.version>
        <javax.mail.version>1.6.2</javax.mail.version>
        <guava.version>32.0.1-android</guava.version>
        <junit-jupiter.version>5.10.0</junit-jupiter.version>
        <commons-text.version>1.12.0</commons-text.version>
        <jacoco.version>0.8.11</jacoco.version>
        <isRoot>true</isRoot>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
        </dependency>

        <!-- 单测相关依赖-->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit-jupiter.version}</version> <!-- 或更高版本 -->
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit-jupiter.version}</version> <!-- 或更高版本 -->
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <version>${junit-jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit-pioneer</groupId>
            <artifactId>junit-pioneer</artifactId>
            <version>2.3.0</version>
        </dependency>
        <!-- Mockito Core -->
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>5.5.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-inline</artifactId>
            <version>4.11.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-junit-jupiter</artifactId>
            <version>5.5.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin.version}</version>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>com.github.therapi</groupId>
                            <artifactId>therapi-runtime-javadoc-scribe</artifactId>
                            <version>${therapi.runtime.javadoc.scribe.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>0.2.0</version>
                        </path>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${mapstruct.version}</version>
                        </path>
                    </annotationProcessorPaths>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                    <release>${maven.compiler.target}</release>
                    <parameters>true</parameters>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <!-- ### 修改后的 Surefire 插件配置（仅支持 JUnit5） ### -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M5</version>
                <configuration>
                    <useSystemClassLoader>false</useSystemClassLoader>
                    <testFailureIgnore>true</testFailureIgnore>
                    <!-- 添加 JUnit 5 提供者 -->
                    <includes>
                        <include>**/*Test.java</include> <!-- 包括 JUnit 4 测试 -->
                        <include>**/*Tests.java</include> <!-- 包括 JUnit 4 测试 -->
                        <include>**/*IT.java</include> <!-- 包括 JUnit 4 测试 -->
                        <include>**/*ITCase.java</include> <!-- 包括 JUnit 4 测试 -->
                        <include>**/*Should.java</include> <!-- 包括 JUnit 5 测试 -->
                        <include>**/*When.java</include> <!-- 包括 JUnit 5 测试 -->
                        <include>**/*Given.java</include> <!-- 包括 JUnit 5 测试 -->
                    </includes>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.junit.vintage</groupId>
                        <artifactId>junit-vintage-engine</artifactId>
                        <version>5.8.2</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
</project>
